services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: ./data_layer
    depends_on:
      - redis
    volumes:
      - ./datalake:/app/datalake
