[project]
name = "data_layer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofile>=3.9.0",
    "aiohttp>=3.12.15",
    "asyncio>=4.0.0",
    "requests>=2.32.5",
]
